### ISSUE TITLE
Review of previous techniques used for recovery

### ISSUE THREAD

**Issue by bytecod3** [nakujaproject/recoveryN3#1]
This includes: 
1. Communication to detect apogee
2. Pyrotechnic ejection

**Comment by JonesKisaka** [comment]
Noted with Thanks. Sent from Mail for Windows From: #EduhSent: Thursday, January 26, 2023 12:46 AMTo: nakujaproject/recoveryN3Cc: Kisaka the Jones; AssignSubject: Re: [nakujaproject/recoveryN3] Review of previous techniques used for recovery (Issue #1) Closed #1 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
